### ISSUE TITLE
Kemiasok kerdesei az infos fogalmak/megnevezesek kapcsan

### ISSUE THREAD

**Issue by PocsGeza** [LaszloBarabasUBB/iotwithchem#3]
Akinek kerdesei vannak az infos fogalmak/megevezesek kapcsan beleirhatja ebbe az issue-ba.
A kovetkezo formatumot hasznaljuk:
Nev: Kerdes
Pl. "Nagy Bela: Mit jelent a REST hivas?"

Ha kerdezo kielegito valaszt kapott akkor kerjuk lepjen vissza es modositsa a bejegyzeset.

Pl. "Nagy Bela: Mit jelent a REST hivas? - Megvan"

**Comment by LaszloBarabasUBB** [comment]
Keszulok es megyek a kemiasokhoz.

**Comment by LaszloBarabasUBB** [comment]
Kemiasok, kepesek beuzemelni es hasznali egyedul az alkalmazast.
